### ISSUE TITLE
how to fix KeyError: 'pred_vfov'.

### ISSUE THREAD

**Issue by alubawzk** [jinlinyi/PerspectiveFields#17]
Hi, Jinlin:

Thanks for your publicly available codes. I tried the demo.py as follows.
```python
python demo/demo.py \
--config-file models/cvpr2023.yaml \
--input assets/imgs \
--output output \
--opts MODEL.WEIGHTS /data/wzk/Perspective_Fields/models/cvpr2023.pth
``` 
But I got this error:
```shell
Traceback (most recent call last):
  File "/home/wzk2019/PerspectiveFields-main/demo/demo.py", line 448, in <module>
    save_vis(demo, img, predictions, output_folder=output_f)
  File "/home/wzk2019/PerspectiveFields-main/demo/demo.py", line 317, in save_vis
    pred['pred_general_vfov'] = pred['pred_vfov']
KeyError: 'pred_vfov'
``` 
I printed the keys of 'pred' in demo.py, then got these
```python
dict_keys(['pred_gravity', 'pred_gravity_original', 'pred_latitude', 'pred_latitude_original', 'pred_latitude_original_mode']).
``` 
Is there something wrong with my operation?

Thanks.

**Comment by alubawzk** [comment]
By the way, it works when I replace 'cvpr2023' with 'paramnet_gsv_rpf'. But still cant run with 'cvpr2023'.

**Comment by jinlinyi** [comment]
Hi this is because this "cvpr2023" model does not predict camera parameters and the demo script didn't handle this. I've updated the script.
